### ISSUE TITLE
repeating error when executing docker

### ISSUE THREAD

**Issue by jazzyjas** [minhng92/odoo-14-docker-compose#3]
# Repeating error while executing

Sorry to bother you yet another time, but since I changed the web.base url, I keep getting the following error int the console:

```
db_1      | 2021-05-25 17:04:42.682 UTC [2640] ERROR:  could not obtain lock on row in relation "ir_cron"
db_1      | 2021-05-25 17:04:42.682 UTC [2640] STATEMENT:  SELECT id FROM "ir_cron" WHERE id IN (7) FOR UPDATE NOWAIT
db_1      | 2021-05-25 17:09:43.539 UTC [39] ERROR:  could not obtain lock on row in relation "ir_cron"
db_1      | 2021-05-25 17:09:43.539 UTC [39] STATEMENT:  SELECT id FROM "ir_cron" WHERE id IN (7) FOR UPDATE NOWAIT
db_1      | 2021-05-25 17:14:44.453 UTC [34] ERROR:  could not obtain lock on row in relation "ir_cron"
db_1      | 2021-05-25 17:14:44.453 UTC [34] STATEMENT:  SELECT id FROM "ir_cron" WHERE id IN (7) FOR U
```

and so on every five minutes. Also, after a while the web.base.url changes back to what it was.. -> 
do you have any advice?

**Comment by minhng92** [comment]
Hi @jazzyjas ,

In order to freeze the "web.base.url", we add a new key "**web.base.url.freeze**" with "**True**" value to the _System Parameters_.
As the following link (Yenthe's answer):
[https://www.odoo.com/es_ES/forum/ayuda-1/system-parameters-web-base-url-143575](https://www.odoo.com/es_ES/forum/ayuda-1/system-parameters-web-base-url-143575)

I'm not sure about the error message, I think you should restart the Odoo container / Odoo server.
